### ISSUE TITLE
secret for a service account

### ISSUE THREAD

**Issue by balagurrr** [yandex-cloud/provider-jet-yc#4]
please do the secret creation for the service account like this

`yc iam key create iamkey \
 --service-account-id=<your service account ID> 
 --format=json \
 --output=iamkey.json`

**Comment by nar3k** [comment]
Do you mean that you need static key resource that renders json key in crossplane? @balagurrr

**Comment by balagurrr** [comment]
I need like this

```
apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: ServiceAccountKey
metadata:
  name: example-sa-key
spec:
  forProvider:
    description: "service account key"
    serviceAccountIdRef:
      name: example-sa
  providerConfigRef:
    name: example
  writeConnectionSecretToRef:
    name: sa-key
    namespace: crossplane-system
```
but write to secret json iamkey
this secret need for https://github.com/yandex-cloud/cert-manager-webhook-yandex, for example
