### ISSUE TITLE
AccessKey to secret writeConnectionSecretToRef (kind ServiceAccountStaticAccessKey)

### ISSUE THREAD

**Issue by balagurrr** [yandex-cloud/provider-jet-yc#5]
Please, add AccessKey to secret writeConnectionSecretToRef (kind ServiceAccountStaticAccessKey):

```
kind: ServiceAccountStaticAccessKey
spec:
  writeConnectionSecretToRef:
    name: sa-key-conn
    namespace: crossplane-system
```
    
attribute.access_key (for example)
